server:
  port: 7070
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix : classpath:/templates/
    suffix : .html
    cache : false
    mode : HTML5
    encodeing : UTF-8
#   resources:
#    chain.strategy.content.enabled: true
#    spring.resources.chain.strategy.content.paths: /**
mybatis:
  mapper-locations: classpath*:mapper/*.xml
